#!/usr/bin/env bash
# Transfers a file from a client to a server.

i=1
for arg in "$@"
do
	i=$((i + 1))
done

if [ "$i" -le 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
