#!/usr/bin/env bash
# Configures a new ubuntu machine to install nginx and listen on port 80
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
cd /var/www/html
sudo mv index.nginx-debian.html index-a.nginx-debian.html
sudo echo "Hello World!" > index.nginx-debian.html
sudo service nginx restart
