#!/usr/bin/env bash
# This script is diplaying "Best School" 10 times using `while` loop.
# But for the 9 th iteration, displays `Best School` and then `Hi` on a new line

i=1

while [ $i -lt 10 ]
do
	if [ $i == 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	i=$((i+1))
done
