#!/usr/bin/env bash
# This script is diplaying "Best School" 10 times using `while` loop.
# But for the 4th iteration, displays `bad luck`.
# But for the 9 th iteration, displays `good luck`.

i=1

while [ $i -lt 11 ]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	i=$((i+1))
done
